### ISSUE TITLE
Doces x Salgadas

### ISSUE THREAD

**Issue by romanosw** [mullinga/cuca-chanfres#1]
O balanceamento entre sabores doces x salgados não está sendo realizado de maneira correta.

Níveis de robustez devem ser inseridos para garantir que:

* caso o número de cucas pedido seja par, tenha-se metade de cucas salgadas e metade, doces;
* caso o numero de cucas pedido seja ímpar, tenha-se uma cuca doce à mais do que o número total de cucas salgadas.

**Comment by mullinga** [comment]
Devo lembrar que o projeto visa automatizar o evento da cuca através de um sistema de aviso luminoso durante o dia da Cuca. Sendo assim, não serão levados em conta, em um primeiro momento, outras sugestões sobre a logística de compra da cuca

Att, Matias de Andrea
